apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-java-backend
  namespace: argocd
spec:
  project: default

  source:
    # 你的 GitHub 仓库地址
    repoURL: https://github.com/uchihaph/my-java-backend-demo.git
    targetRevision: main
    # YAML 所在的目录
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
