apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-java-backend
  namespace: argocd
  annotations:
    # 告诉 AIU 监控这个 Application 下的镜像
    argocd-image-updater.argoproj.io/image-list: myapp=uchihaph/my-java-backend
    argocd-image-updater.argoproj.io/myapp.update-strategy: newest-build
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^latest$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/uchihaph/my-java-backend-demo.git
    targetRevision: main
    path: k8s
    kustomize:
      commonAnnotations:
        managed-by: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
