apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# prod 环境：3 个副本（高可用）
replicas:
  - name: backend-deploy
    count: 3

images:
  - name: uchihaph/my-java-backend
    newTag: latest

namespace: prod
