apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
        volumeMounts:
        # 挂载到 Redis 的数据目录
        - name: redis-data
          mountPath: /data
        # 让 Redis 开启 AOF 持久化（数据实时落盘）
        command: ["redis-server", "--appendonly", "yes"]
        
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: redis-data
        hostPath:
          # 数据存到数据盘
          path: /data/project/testdocker/redis-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379