apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

replicas:
  - name: backend-deploy
    count: 1

images:
  - name: uchihaph/my-java-backend
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: my-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.hanguo.bbroot.com
